### ISSUE TITLE
Is JTech Real?

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork/ConnectOneTwo#17]

**Comment by smileycreations15** [comment]
IMO he treats it as real but it isn't.

**Comment by smileycreations15** [comment]
Is there a website?

**Comment by AfterNetwork** [comment]
> Is there a website?

for wut

**Comment by smileycreations15** [comment]
jtech

**Comment by AfterNetwork** [comment]
this is the closest i could find to a jtech website
https://jbrow78.github.io/

**Comment by smileycreations15** [comment]
well is it even copyrighted 🤔

**Comment by AfterNetwork** [comment]
its open source so i suppose no.

**Comment by smileycreations15** [comment]
mine is

**Comment by AfterNetwork** [comment]
wait so u regestired ur website copyight for how much?

**Comment by smileycreations15** [comment]
no. it is license law.

**Comment by AfterNetwork** [comment]
ok. work on cot.

**Comment by AfterNetwork** [comment]
You haven't contributed to ConnectOneTwo's code in any way.

**Comment by smileycreations15** [comment]
Wait. I have things to do too, I am human.

**Comment by AfterNetwork** [comment]
when can you work on cot

**Comment by smileycreations15** [comment]
not soon

**Comment by AfterNetwork** [comment]
can you give me a date?

**Comment by smileycreations15** [comment]
Not sure.

**Comment by AfterNetwork** [comment]
ok bye

**Comment by smileycreations15** [comment]
wat?

**Comment by AfterNetwork** [comment]
gtg

**Comment by smileycreations15** [comment]
ah bye

**Comment by jbrow78** [comment]
I am getting a website soon

**Comment by AfterNetwork** [comment]
stop hiding evidence

**Comment by smileycreations15** [comment]
ok i just noticed this

**Comment by jbrow78** [comment]
No, seriously.

**Comment by jbrow78** [comment]
J Tech is currently in the copyright proccess

**Comment by jbrow78** [comment]
J Tech is now Copyright
